valor = input('Digite algo: ')
print(f'O tipo primitivo de algo é {type(valor)}')
print('Só tem espaços? ', valor.isspace())
print('É alfabético? ', valor.isalpha())
print('É numérico? ', valor.isnumeric())
print('É alfanumérico? ', valor.isalnum())
print('Está em maisúsculas? ', valor.isupper())
print('Está em minúsculas? ', valor.islower())
print('Está capitalizada? ', valor.istitle())
